
<h1>My Videos</h1>
<div class="block block-listview">
    <ul data-role="listview">
        <li><a href="<?=MOBILE_HOST?>/v/4/">
            <div class="video">
                <div class="thumbnail">
                    <img width="107" height="60" src="<?=$this->options->themeUrl?>/images/thumb2.png" />
                    <span class="duration">2:35</span>
                </div>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
        </a>
        </li>
        <li><a href="<?=MOBILE_HOST?>/v/4/">
            <div class="video">
                <div class="thumbnail">
                    <img width="107" height="60" src="<?=$this->options->themeUrl?>/images/thumb3.png" />
                    <span class="duration">7:10</span>
                </div>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
        </a>
        </li>
        <li><a href="<?=MOBILE_HOST?>/v/4/">
            <div class="video">
                <div class="thumbnail">
                    <img width="107" height="60" src="<?=$this->options->themeUrl?>/images/thumb4.png" />
                    <span class="duration">4:50</span>
                </div>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
        </a>
        </li>
        <li data-icon="false" class="load-more"><a href="">Load More</a></li>
    </ul>
</div>
        
