    
<h1><?=Language::getText('search_header')?></h1>
<p><strong><?=Language::getText('results_for')?>:</strong> <?=$keyword?></p>
<div class="block block-listview">
    <ul data-role="listview">
        <?php if (!empty($searchVideos)): ?>
            <?php $this->repeatingBlock('video.phtml', $searchVideos); ?>
        <?php else: ?>
            <li><?=Language::getText('no_results')?></li>
        <?php endif; ?>
    </ul>
</div>

        
  