
<h1><?=Language::getText('videos_header')?></h1>
<div class="block block-listview">
    <ul data-role="listview" class="video-list">
        <?php if (!empty($videos)): ?>
            <?php $this->repeatingBlock('video.phtml', $videos); ?>
        
            <?php if (count($videos) < $count): ?>
                <li data-icon="false" data-count="<?=$count?>" data-limit="20" class="load-more"><a href=""><?=Language::getText('load_more')?></a></li>
            <?php endif; ?>
                
        <?php else: ?>
            <li><?=Language::getText('no_videos')?></li>
        <?php endif; ?>
    </ul>
</div>
        
