        

<h1>Upload a Video</h1>
<div class="block">
    <form>
        <div class="upload-buttons">
            <button class="ui-btn ui-btn-inline button-browse">Browse</button>
            <button class="ui-btn ui-btn-inline button-upload">Upload</button>
        </div>
        <p class="uploaded-file"><a href="" class="ui-btn ui-icon-delete ui-btn-icon-notext ui-corner-all ui-btn-inline">Cancel</a>video_to_post.mp4 (44MB)</p>
        <input type="text" placeholder="Title" name="title" />
        <input type="text" placeholder="Tags" name="Tags" />
        <textarea placeholder="Description" name="description"></textarea>
        <fieldset data-role="controlgroup">
            <input type="checkbox" name="disable-embed" id="disable-embed" checked="">
            <label for="disable-embed">Disable Embed</label>
            <input type="checkbox" name="gated" id="gated" checked="">
            <label for="gated">Gated</label>
            <input type="checkbox" name="private" id="private" checked="">
            <label for="private">Private</label>
            <input type="checkbox" name="comments-closed" id="comments-closed" checked="">
            <label for="comments-closed">Close Comments</label>
        </fieldset>
        <button type="submit" class="ui-btn ui-corner-all">Post Video</button>
    </form>
</div>