<?php $video = $model ?>

<li>
    <a href="<?=MOBILE_HOST?>/v/<?=$video->videoId?>/">
        <div class="video">
            <div class="thumbnail">
                <img width="107" height="60" src="<?=$config->thumbUrl?>/<?=$video->filename?>.jpg" />
                <span class="duration"><?=$video->duration?></span>
            </div>
            <p><?=$video->title?></p>
        </div>
    </a>
</li>
        