
<!-- BEGIN FOOTER -->
<div id="footer">
    <div id="sub_footer">
        <a href="<?=HOST?>/browse/" title="<?=Language::GetText('videos')?>"><?=Language::GetText('videos')?></a>
        <a href="<?=HOST?>/members/" title="<?=Language::GetText('members')?>"><?=Language::GetText('members')?></a>
        <?php if ($config->enableUserUploads): ?>
            <a href="<?=HOST?>/account/upload/video/" title="<?=Language::GetText('upload')?>"><?=Language::GetText('upload')?></a>
        <?php endif; ?>
        <a href="<?=HOST?>/contact/" title="<?=Language::GetText('contact')?>"><?=Language::GetText('contact')?></a>
        <a href="<?=HOST?>/video-sitemap.xml" title="<?=Language::GetText('sitemap')?>"><?=Language::GetText('sitemap')?></a>
    </div>
</div>
<!-- END FOOTER -->