
<!-- BEGIN FOOTER -->
<div id="footer">
    <div id="sub_footer">
        <a href="<?=HOST?>/videos/" title="<?=Language::GetText('videos')?>"><?=Language::GetText('videos')?></a>
        <a href="<?=HOST?>/members/" title="<?=Language::GetText('members')?>"><?=Language::GetText('members')?></a>
        <a href="<?=HOST?>/account/upload/" title="<?=Language::GetText('upload')?>"><?=Language::GetText('upload')?></a>
        <a href="<?=HOST?>/contact/" title="<?=Language::GetCustomText('contact')?>"><?=Language::GetCustomText('contact')?></a>
        <a href="<?=HOST?>/video-sitemap.xml" title="<?=Language::GetCustomText('sitemap')?>"><?=Language::GetCustomText('sitemap')?></a>
    </div>
</div>
<!-- END FOOTER -->