
<div class="form">
    <form action="<?=HOST?>/login/" method="post">
        <label><?=Language::getText('username')?>:</label>
        <input type="text" name="username" value="" />

        <label><?=Language::getText('password')?>:</label>
        <input type="password" name="password" value="" />

        <input type="hidden" name="submitted_login" value="true" />
        <input type="hidden" name="nonce" value="<?php echo $formNonce; ?>" />
        <input class="button" type="submit" value="<?=Language::getText('login_button')?>" />
    </form>
    <?php if ($config->enableRegistrations): ?>
        <div class="divider"></div>
        <p><a href="<?=HOST?>/register/"><?=Language::getText('no_account')?></a></p>
    <?php endif; ?>
</div>
