<h1><?=Language::GetText('videos_header')?></h1>
<p class="large"><?=Language::GetText('viewing')?>: <?=$sub_header?></p>


<div>
    <div id="sort_options">
        <p class="big"><?=Language::GetText('sorting')?></p>
        <p><a href="<?=HOST?>/browse/most-recent/" title="<?=Language::GetText('most_recent')?>"><?=Language::GetText('most_recent')?></a><br />
        <a href="<?=HOST?>/browse/most-viewed/" title="<?=Language::GetText('most_viewed')?>"><?=Language::GetText('most_viewed')?></a><br />
        <a href="<?=HOST?>/browse/most-discussed/" title="<?=Language::GetText('most_discussed')?>"><?=Language::GetText('most_discussed')?></a><br />
        <a href="<?=HOST?>/browse/most-rated/" title="<?=Language::GetText('most_rated')?>"><?=Language::GetText('most_rated')?></a></p>
    </div>

    <div id="category_options">
        <p class="big"><?=Language::GetText('category')?></p>
        <ul>
        <?php foreach ($category_list as $category): ?>
            <li><a href="<?=HOST?>/browse/<?=$category->slug?>/" title="<?=$category->name?>"><?=$category->name?></a></li>
        <?php endforeach; ?>
        </ul>
    </div>
    <div class="clear"></div>
</div>

<?php if (!empty ($browse_videos)): ?>
    <div class="videos_list">
        <?php $this->RepeatingBlock('video.phtml', $browse_videos); ?>
    </div>
    <?=$pagination->Paginate()?>
<?php else: ?>
    <p><strong><?=Language::GetText('no_videos')?></strong></p>
<?php endif; ?>