<!DOCTYPE html>
<html>
<head>
<title><?=$video->title?></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet" href="<?=$this->options->themeUrl?>/css/reset.css" />
<style type="text/css">
html, body, .video-unavailable, video, img {
    width:100% !important;
    height:100% !important;
    overflow:hidden;
}
.video-unavailable {
    background-color:#000;
    text-align:center;
    color:#FFF;
    font-size:16px;
    font-family:arial,helvetica,sans-serif;
}
.video-unavailable p {
    padding:50px;
    line-height:1.5em;
}
</style>
<body>

<?php if ($video && $video->disableEmbed == '0'): ?>

    <!-- BEGIN VIDEO -->
    <video controls="controls" poster="<?=$config->thumb_url?>/<?=$video->filename?>.jpg">
        <source src="<?=$config->h264Url?>/<?=$video->filename?>.mp4" type="video/mp4" />
        <source src="<?=$config->theoraUrl?>/<?=$video->filename?>.ogv" type="video/ogg" />
        <?php if ($vp8Options->enabled): ?>
            <source src="<?=$config->vp8Url?>/<?=$video->filename?>.webm" type="video/webm" />
        <?php endif; ?>
    </video>
    <!-- END VIDEO -->

<?php elseif ($video && $video->disableEmbed == '1'): ?>
    <?php $link = $this->getService('Video')->getUrl($video) . '/'; ?>
    <div class="video-unavailable"><p><?=Language::getText('embed_disabled', array ('link' => $link, 'sitename' => $config->sitename))?></p></div>
<?php else: ?>
    <div class="video-unavailable"><p><?=Language::getText('video_unavailable')?></p></div>
<?php endif; ?>

</body>
</html>