<h1><?=Language::GetText('members_header')?></h1>

<?php if (count($userResults) > 0): ?>
    <div class="member_list">
    <?php $userService = $this->getService('User'); ?>
    <?php foreach ($userResults as $member): ?>
        <div>
            <p class="avatar"><a href="<?=HOST?>/members/<?=$member->username?>/" title="<?=$member->username?>">
                <?php $avatar = $this->getService('User')->getAvatarUrl($member); ?>
                <img src="<?=($avatar) ? $avatar : $this->options->themeUrl . '/images/avatar.gif'?>" alt="<?=$member->username?>" />
            </a></p>
            <a href="<?=HOST?>/members/<?=$member->username?>/" title="<?=$member->username?>"><?=Functions::CutOff($member->username,18)?></a>
            <p><strong><?=Language::GetText('joined')?>: </strong><?=date('m/d/Y', strtotime($member->dateCreated))?></p>
            <p><strong><?=Language::GetText('videos')?>: </strong><?=$userService->getVideoCount($member)?></p>
        </div>
    <?php endforeach; ?>
    </div>
    <?=$pagination->Paginate()?>

<?php else: ?>
    <p><strong><?=Language::GetText('no_members')?></strong></p>
<?php endif; ?>