<?php
$this->addCss('video-js.css');
$this->addJs('video.js');
$this->addJs('play.js');
?>

<div id="play">
    <div class="block">
        
        <h1><?=$video->title?></h1>

        <div class="video-js-box">
            <video class="video-js" width="100%" height="264" controls preload poster="<?=$config->thumbUrl?>/<?=$video->filename?>.jpg">

                <source src="<?=$config->mobileUrl?>/<?=$video->filename?>.mp4" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"' />
                <object id="flash_fallback_1" class="vjs-flash-fallback" width="100%" height="264" type="application/x-shockwave-flash" data="http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf">
                    <param name="movie" value="http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf" />
                    <param name="allowfullscreen" value="true" />
                    <param name="flashvars" value='config={"playlist":["<?=$config->thumbUrl?>/<?=$video->filename?>.jpg", {"url": "<?=$config->mobileUrl?>/<?=$video->filename?>.mp4","autoPlay":false,"autoBuffering":true}]}' />
                    <img src="<?=$config->mobileUrl?>/<?=$video->filename?>.jpg" width="100%" height="264" alt="Poster Image" title="No video playback capabilities." />
                </object>

            </video>
        </div>

        <p><strong><?=Language::getText('duration')?>: </strong><?=$video->duration?></p>
        <p><strong><?=Language::getText('by')?>: </strong><?=$video->username?></p>
        <p><strong><?=Language::getText('description')?>: </strong><?=$video->description?></p>
                
    </div>
</div>