<?php $this->SetLayout('account'); ?>

<h1><?=Language::GetText('message_read_header')?></h1>
<div id="message_display">
    <p><a href="<?=HOST?>/account/message/inbox/" title="<?=Language::GetText('return_inbox')?>"><?=Language::GetText('return_inbox')?></a></p>
    <p><strong><?=Language::GetText('sender')?>: </strong>&nbsp;&nbsp;&nbsp;<?=$message->username?></p>
    <p><strong><?=Language::GetText('date')?>: </strong>&nbsp;&nbsp;&nbsp;<?=date('m/d/Y', strtotime($message->dateCreated))?></p>
    <p><strong><?=Language::GetText('subject')?>: </strong>&nbsp;&nbsp;&nbsp;<?=htmlspecialchars($message->subject)?></p>
    <div id="message_body"><?=nl2br(htmlspecialchars($message->message))?></div>
    <a class="button" href="<?=HOST?>/account/message/reply/<?=$message->messageId?>/"><?=Language::GetText('reply')?></a>
    <a class="button confirm" data-node="confirm_delete_message" href="<?=HOST?>/account/message/inbox/<?=$message->messageId?>/"><?=Language::GetText('delete')?></a>
</div>