<?php
$this->addJs('fileupload.jquery-ui.widget.js');
$this->addJs('fileupload.iframe-transport.js');
$this->addJs('fileupload.plugin.js');
$this->addJs('fileupload.js');
$this->setLayout('account');
?>

<h1><?=Language::getText('upload_video_header')?></h1>

<div class="message"></div>

<p><?=Language::getText('upload_video_text')?></p>
<p class="big"><?=Language::getText('filesize_limit')?>: <?=round($config->videoSizeLimit/1048576)?>MB</p>
<p class="big"><?=Language::getText('upload_supported_formats') . ': ' . implode(', ', $config->acceptedVideoFormats)?></p>

<form action="<?=HOST?>/account/upload/video/" method="post">

    <div class="uploader-wrapper">
        <input
            class="uploader"
            type="file"
            name="upload"
            data-url="<?=HOST?>/ajax/upload/"
            data-text="<?php echo Language::getText('browse_files_button'); ?>"
            data-limit="<?php echo 1024*1024*1024*1; ?>"
            data-extensions="<?php echo urlencode(json_encode(array('mp4'))); ?>"
            data-type="video"
            data-start-upload-button="<?=Language::getText('start_upload_button')?>"
            data-auto-submit="true"
        />
    </div>

    <input type="hidden" name="submitted" value="true" />

</form>
